apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap-sql
  namespace: experio
data:
  init.sql: |
    ALTER DATABASE odoodb OWNER TO expuser;

---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: expcluster
  namespace: experio
spec:
  postgresVersion: 17
  users:
    - name: expuser
      databases:
        - odoodb
  databaseInitSQL:
    name: bootstrap-sql
    key: init.sql
  instances:
    - name: pgha1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: expcluster
                    postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  proxy:
    pgBouncer:
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: expcluster
                    postgres-operator.crunchydata.com/role: pgbouncer
  patroni:
    dynamicConfiguration:
      bootstrap:
        dcs:
          postgresql:
            parameters:
              shared_preload_libraries: 'pg_stat_statements'
