apiVersion: v1
kind: Secret
metadata:
  name: expcluster-pguser-expuser
  labels:
    postgres-operator.crunchydata.com/cluster: expcluster
    postgres-operator.crunchydata.com/pguser: expuser

# type: Opaque
# data:
#   password: YWRtaW4= # base64 encoded password (admin)

stringData:
  password: admin